// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  anchor: defineAsyncComponent(() => import("./Anchor/index.vue")),
  contact: defineAsyncComponent(() => import("./Contact/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  header: defineAsyncComponent(() => import("./Header/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  image_cards: defineAsyncComponent(() => import("./ImageCards/index.vue")),
  map: defineAsyncComponent(() => import("./Map/index.vue")),
  metamorphosis: defineAsyncComponent(
    () => import("./Metamorphoses/index.vue"),
  ),
  portraits: defineAsyncComponent(() => import("./Portraits/index.vue")),
  pricelist: defineAsyncComponent(() => import("./Pricelist/index.vue")),
  quote: defineAsyncComponent(() => import("./Quote/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
  text_with_image: defineAsyncComponent(
    () => import("./TextWithImage/index.vue"),
  ),
  tiles: defineAsyncComponent(() => import("./Tiles/index.vue")),
});
